import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ArrowRight,ChevronDown,Menu,X,MessageCircle,MapPin,Instagram}from"lucide-react";import"./styles.css";
const WA="263771905540";const wa=(m="Hello Teecherz, I'd like to enquire about furniture.")=>`https://wa.me/${WA}?text=${encodeURIComponent(m)}`;
const img={living1:"https://teecherz.com/wp-content/uploads/2021/01/DSC_1565-2-300x225.jpeg",living2:"https://teecherz.com/wp-content/uploads/2021/02/sofa.jpg",bed1:"https://teecherz.com/wp-content/uploads/2021/01/Oxford-Bedroom-Suite-11-Usd793-Excluding-Kist-2-300x225.jpeg",bed2:"https://teecherz.com/wp-content/uploads/2021/02/bedroom.jpg",bed3:"https://teecherz.com/wp-content/uploads/2021/02/suite-300x225.jpg",dining1:"https://teecherz.com/wp-content/uploads/2021/02/Sasha-.jpg",dining2:"https://teecherz.com/wp-content/uploads/2021/02/harvard.jpg",office1:"https://teecherz.com/wp-content/uploads/2020/07/Pic35-scaled.jpg",office2:"https://teecherz.com/wp-content/uploads/2020/07/63-scaled-300x225.jpg",office3:"https://teecherz.com/wp-content/uploads/2020/07/69-scaled-300x225.jpg"};
const products=[["Santiago Lounge Suite","Living",img.living2],["Pristine Lounge Suite","Living",img.living1],["Emperor Bedroom Suite","Bedroom",img.bed2],["Oxford Bedroom Suite","Bedroom",img.bed1],["Lincoln Bedroom Suite","Bedroom",img.bed3],["Sasha Dining Suite","Dining",img.dining1],["GAD Dining Room Suite","Dining",img.dining2],["Falcon Mesh High Back Chair","Office",img.office2],["Cambridge Swivel Chair","Office",img.office3],["Office filing cabinet","Office",img.office1]];
const rooms=[["Living","Comfort beyond your needs",img.living2],["Dining","Memorable moments with family",img.dining1],["Bedroom","Timeless elegance",img.bed2],["Office","Modern solutions",img.office2]];
const branches=["Manhattan — 46 Cnr L. Takawira & Robert Mugabe","Unity Court — 64 Kwame Nkrumah Ave","Robert Mugabe — 85–87 Robert Mugabe Road","Westgate — Westgate Shopping Mall","Cabs Centre — 74 Jason Moyo Street","Nature House — 13 First Street","Karigamombe — Karigamombe Centre","Bulawayo Centre — Shop 20 Bulawayo Centre"];
function App(){const[open,setOpen]=useState(false);const[filter,setFilter]=useState("All");const shown=filter==="All"?products:products.filter(p=>p[1]===filter);const goToCollection=(category)=>{setFilter(category);setOpen(false);requestAnimationFrame(()=>document.getElementById("collection")?.scrollIntoView({behavior:"smooth",block:"start"}));};return <div>
<div className="concept">Independent website concept · Not the official Teecherz website</div>
<header><a className="brand" href="#">TEECHERZ<span>HOME & OFFICE</span></a><nav>{["Living","Dining","Bedroom","Office"].map(x=><a href="#collection" onClick={(e)=>{e.preventDefault();goToCollection(x)}} key={x}>{x}</a>)}<a href="#branches">Branches</a><a href="#about">About</a></nav><a className="navwa" href={wa()}><MessageCircle size={16}/> WhatsApp</a><button className="menub" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobileNav">{["Living","Dining","Bedroom","Office"].map(x=><a onClick={(e)=>{e.preventDefault();goToCollection(x)}} href="#collection" key={x}>{x}</a>)}<a onClick={()=>setOpen(false)} href="#branches">Branches</a><a onClick={()=>setOpen(false)} href="#about">About</a><a href={wa()}>WhatsApp an enquiry</a></div>}
<main>
<section className="hero"><div className="heroCopy"><p className="kicker">SINCE 1994 · ZIMBABWE</p><h1>Furniture for the way Zimbabwe <em>lives and works.</em></h1><p className="lede">A considered collection for living rooms, bedrooms, dining spaces and the modern office — presented around the way you actually use them.</p><div className="actions"><a className="darkBtn" href="#collection">Explore the collection <ArrowRight size={17}/></a><a className="textBtn" href={wa()}>Talk to Teecherz <ArrowRight size={17}/></a></div></div><div className="heroImage"><img src={img.living2} alt="Teecherz lounge furniture showroom" fetchpriority="high"/><div className="heroTag"><span>01</span><strong>The living room</strong><small>Santiago Lounge Suite</small></div></div></section>
<section className="marquee"><span>HOME</span><span>OFFICE</span><span>LIVING</span><span>DINING</span><span>BEDROOM</span><span>HOME</span></section>
<section className="rooms section" id="living"><div className="sectionHead"><div><p className="kicker">SHOP BY ROOM</p><h2>Spaces with a point of view.</h2></div><p>Start with the room, then discover pieces that belong there.</p></div><div className="roomGrid">{rooms.map((r,i)=><a className={"room room"+i} href="#collection" onClick={(e)=>{e.preventDefault();goToCollection(r[0])}} key={r[0]}><img src={r[2]} alt={r[0]+" furniture"} loading="lazy"/><div><small>{String(i+1).padStart(2,"0")} · {r[1]}</small><h3>{r[0]}</h3><span>{r[1]} <ArrowRight size={15}/></span></div></a>)}</div></section>
<section className="split section" id="about"><div className="splitImage"><img src={img.office1} alt="Teecherz office furniture" loading="lazy"/></div><div className="splitCopy"><p className="kicker">THE TEECHERZ STORY</p><h2>Built around Zimbabwean homes and businesses.</h2><p>Teecherz Home & Office was founded in July 1994 and operates a branch network serving customers across Zimbabwe.</p><div className="facts"><div><b>1994</b><span>Founded in July</span></div><div><b>Nationwide</b><span>Branch network</span></div><div><b>12 months</b><span>Published guarantee</span></div></div></div></section>
<section className="catalog section" id="collection"><div className="sectionHead"><div><p className="kicker">THE COLLECTION</p><h2>From the showroom floor.</h2></div><a className="textBtn" href={wa("Hello Teecherz, I'd like to browse your current furniture range.")}>Ask about the current range <ArrowRight size={17}/></a></div><div className="filters">{["All","Living","Dining","Bedroom","Office"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="productGrid">{shown.map((p,i)=><article className="product" key={p[0]}><a href={wa(`Hello Teecherz, I'd like to enquire about the ${p[0]}. Is it currently available?`)}><div className="productImage"><img src={p[2]} alt={p[0]} loading="lazy"/><span>Enquire <ArrowRight size={14}/></span></div><div className="productMeta"><small>{p[1]}</small><h3>{p[0]}</h3></div></a></article>)}</div></section>
<section className="darkPanel" id="branches"><div><p className="kicker">FIND A SHOWROOM</p><h2>Closer to home.</h2><p>Teecherz has branches in Harare and towns across Zimbabwe. Ask the team for the nearest branch and current availability.</p><a className="lightBtn" href={wa("Hello Teecherz, please tell me the nearest branch to me.")}>Find my nearest branch <MapPin size={16}/></a></div><div className="branchList">{branches.map((b,i)=><div key={b}><span>{String(i+1).padStart(2,"0")}</span><p>{b}</p></div>)}</div></section>
<section className="cta"><p className="kicker">READY WHEN YOU ARE</p><h2>Seen something you like?</h2><p>Send the piece name and your town. The Teecherz team can confirm availability, pricing and your nearest branch.</p><a className="darkBtn" href={wa()}>Start a WhatsApp enquiry <MessageCircle size={17}/></a></section>
</main>
<footer><div><a className="brand light" href="#">TEECHERZ<span>HOME & OFFICE</span></a><p>Furniture for the way Zimbabwe lives and works.</p></div><div><small>CONTACT</small><a href={wa()}>+263 771 905 540</a><a href="mailto:customercare@teecherz.co.zw">customercare@teecherz.co.zw</a><a href="mailto:customerservice@teecherz.co.zw">customerservice@teecherz.co.zw</a></div><div><small>OFFICIAL WEBSITE</small><a href="https://teecherz.com" target="_blank">teecherz.com</a><a href="#collection">Browse collection</a><a href="#branches">Branches</a></div></footer>
<div className="disclaimer">Independent website concept / sales demo. Product photography and published business facts are used from Teecherz's public website for demonstration. No affiliation or endorsement is implied.</div>
</div>}createRoot(document.getElementById("root")).render(<App/>);